// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/audit" | "/book" | "/bookings" | "/bookings/[id]" | "/calendar" | "/customers" | "/customers/[id]" | "/dashboard" | "/expenses" | "/invoices" | "/invoices/[id]" | "/jobs" | "/jobs/[id]" | "/login" | "/payments" | "/payroll" | "/quotes" | "/reports" | "/services" | "/settings" | "/staff" | "/staff/[id]" | "/users"
type AppRouteHandlerRoutes = "/api/actions/[name]" | "/api/actions/batch" | "/api/ai/chat" | "/api/auth" | "/api/book" | "/api/notifications" | "/api/upload"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/actions/[name]": { "name": string; }
  "/api/actions/batch": {}
  "/api/ai/chat": {}
  "/api/auth": {}
  "/api/book": {}
  "/api/notifications": {}
  "/api/upload": {}
  "/audit": {}
  "/book": {}
  "/bookings": {}
  "/bookings/[id]": { "id": string; }
  "/calendar": {}
  "/customers": {}
  "/customers/[id]": { "id": string; }
  "/dashboard": {}
  "/expenses": {}
  "/invoices": {}
  "/invoices/[id]": { "id": string; }
  "/jobs": {}
  "/jobs/[id]": { "id": string; }
  "/login": {}
  "/payments": {}
  "/payroll": {}
  "/quotes": {}
  "/reports": {}
  "/services": {}
  "/settings": {}
  "/staff": {}
  "/staff/[id]": { "id": string; }
  "/users": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
